// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Main
#include "../Includes/Common.hlsl"
#include "../Includes/RaymarchingHelpers.hlsl"

float2 _ChunkOrigin;
float2 _ChunkSize;
float3 _SunDirection;
float _ShadowEpsilon;
int _MaxSteps;
float _DistanceForHit;
float _SunAngularRadius;
static const float sPi = 3.14159265359;

Texture2D<float> _HeightMap;
RWTexture2D<float> _Result;

uint Hash(uint x)
{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

float Rand(inout uint seed)
{
    seed = Hash(seed);
    // Take lower 24 bits and normalize
    return (seed & 0x00FFFFFFu) / 16777216.0f; // 2^24
}

void MakeOrthonormalBasis(float3 n, out float3 t, out float3 b)
{
    float3 up = (abs(n.z) < 0.999f) ? float3(0, 0, 1) : float3(0, 1, 0);
    t = normalize(cross(up, n));
    b = cross(n, t);
}

float3 SampleConeDirection(float3 axis, float cosMax, float2 u)
{
    float cosTheta = lerp(cosMax, 1.0f, u.x);
    float sinTheta = sqrt(max(0.0f, 1.0f - cosTheta * cosTheta));
    float phi = 2.0f * sPi * u.y;

    float3 t, b;
    MakeOrthonormalBasis(axis, t, b);

    return normalize(t * (cos(phi) * sinTheta) + b * (sin(phi) * sinTheta) + axis * cosTheta);
}

bool MarchedShadows(float3 ro, float3 rd, uint seedBase, out float hitT)
{
    float visibility = 0.0f;

    rd = normalize(rd);

    float3 rayStart = ro;
    float sunHeight = saturate(rd.y);
    float cosMax = cos(max(radians(_SunAngularRadius), 1e-6f));
    float2 u;


    uint seed = seedBase + 9781u;
    u = float2(Rand(seed), Rand(seed));
        
    float3 lightDir = SampleConeDirection(rd, cosMax, u);

    hitT = 1.f;
    float heightTerrain = 0.f;
    bool blocked = false;
        
    float res = 1.f;
        
    //if (_UseRaymarchOptimization)
    //    blocked = TraverseHeightfieldMaxMipShadow(ro, lightDir, t, heightTerrain, _ShadowHitDistance, res, _HeightMap, _ChunkSize, linearClampSampler, _ShadowStepsOptimized, _ShdowEpsilonOptimized);
    //else
    blocked = Raymarch(ro, lightDir, hitT, heightTerrain, _MaxSteps, _DistanceForHit, 1e-2f, _ChunkSize, _HeightMap, linearClampSampler);
    return blocked;
}

[numthreads(16, 16, 1)]
void Main (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    uint2 dims;
    _Result.GetDimensions(dims.x, dims.y);

    float2 uv = (id.xy + 0.5) / dims;
    float2 worldXZ = uv * _ChunkSize;
    float height = _HeightMap.SampleLevel(linearClampSampler, uv, 0);

    float3 worldPos = float3(worldXZ.x, height, worldXZ.y);
    float3 rd = -normalize(_SunDirection); // terrain -> sun
    float3 ro = worldPos + rd * _ShadowEpsilon;
    float hitT = 0.f;
    bool hit = MarchedShadows(ro, rd, Hash(id.x + id.y * dims.x) + _FrameIndex, hitT);
    
    _Result[id.xy] = hit;
}
