// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Main
#include "../Includes/Common.hlsl"
#include "../Includes/RaymarchingHelpers.hlsl"


float3 _SunDirection;
float _ShadowEpsilon;
int _MaxSteps;
float _DistanceForHit;
float _SunAngularRadius;
uint _ConvergeShadows;

static const float sPi = 3.14159265359;

Texture2DArray<float> _HeightMapArray;
RWTexture2DArray<float2> _Result;
Texture2DArray<float2> _ResultPrev;

StructuredBuffer<ChunkData> _Chunks;
int _ChunkCount;

//RWTexture2D<float2> _TemporalShadow;
//Texture2D<float2> _TemporalShadowPrev;

uint Hash(uint x)
{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

float Rand(inout uint seed)
{
    seed = Hash(seed);
    // Take lower 24 bits and normalize
    return (seed & 0x00FFFFFFu) / 16777216.0f; // 2^24
}

void MakeOrthonormalBasis(float3 n, out float3 t, out float3 b)
{
    float3 up = (abs(n.z) < 0.999f) ? float3(0, 0, 1) : float3(0, 1, 0);
    t = normalize(cross(up, n));
    b = cross(n, t);
}

float3 SampleConeDirection(float3 axis, float cosMax, float2 u)
{
    float cosTheta = lerp(cosMax, 1.0f, u.x);
    float sinTheta = sqrt(max(0.0f, 1.0f - cosTheta * cosTheta));
    float phi = 2.0f * sPi * u.y;

    float3 t, b;
    MakeOrthonormalBasis(axis, t, b);

    return normalize(t * (cos(phi) * sinTheta) + b * (sin(phi) * sinTheta) + axis * cosTheta);
}

bool MarchedShadows(float3 ro, float3 rd, uint seedBase, out float hitT)
{
    float visibility = 0.0f;

    rd = normalize(rd);

    float sunHeight = saturate(rd.y);
    float cosMax = cos(max(radians(_SunAngularRadius), 1e-6f));
    float2 u;

    uint seed = seedBase + 9781u;
    u = float2(Rand(seed), Rand(seed));
        
    float3 lightDir = SampleConeDirection(rd, cosMax, u);
   // float3 lightDir = rd;

    bool hit = false;
    float closestT = 1e20;
    float closestElevation = 0.0;

    for (int i = 0; i < _ChunkCount; i++)
    {
        
        ChunkData chunk = _Chunks[i];
        float elevation;
        float2 chunkSize = ((chunk.boundsMax - chunk.boundsMin)).xz;
        
        float3 roLocal = mul(chunk.worldToLocal, float4(ro, 1.0)).xyz;
        float3 rdLocal = normalize(mul((float3x3) chunk.worldToLocal, lightDir));

        //hit = RaymarchChunk(roLocal, rdLocal, hitT, elevation, _MaxSteps, _DistanceForHit, 2e-4, chunkSize, 1.f, chunk.boundsMin, _HeightMapArray, i, linearClampSampler);
        hit = TraverseHeightfieldMaxMipShadowChunk(roLocal, rdLocal, hitT, elevation, _DistanceForHit, _HeightMapArray, chunk.heightSlice, chunkSize, linearClampSampler, _MaxSteps, _ShadowEpsilon, chunk.boundsMin);
        if (hit)
        {
            hit = true;
            closestT = hitT;
            closestElevation = elevation;
           break;
        }
    }
    
    hitT = closestT;
    return hit;
}

[numthreads(8, 8, 1)]
void Main(uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    uint4 dims;
    _Result.GetDimensions(dims.x, dims.y, dims.z);
    
    if (id.x >= dims.x || id.y >= dims.y ||  id.z >= _ChunkCount)
        return;
    
    ChunkData chunk = _Chunks[id.z];

    float2 uv = (float2(id.xy) + 0.5) / float2(dims.x, dims.y);

    float2 worldMin = chunk.offset.xz + chunk.boundsMin.xz * chunk.scale.xz;
    float2 worldMax = chunk.offset.xz + chunk.boundsMax.xz * chunk.scale.xz;
    float2 worldXZ = lerp(worldMin, worldMax, uv);

    float heightSample = _HeightMapArray.SampleLevel(
        linearClampSampler,
        float3(uv, chunk.heightSlice),
        0
    );

    float worldY = heightSample * chunk.scale.y + chunk.offset.y;

    float3 worldPos = float3(worldXZ.x, worldY, worldXZ.y);

    float3 rd = -normalize(_SunDirection);
    float3 ro = worldPos + float3(0, _ShadowEpsilon, 0) + rd * _ShadowEpsilon;

    uint seed = Hash(id.x + id.y * dims.x + id.z * dims.x * dims.y) + _FrameIndex;

    float hitT = 0.0;
    bool hit = MarchedShadows(ro, rd, seed, hitT);
    
    
    float shadow = hit ? AMBIENT_INTENSITY : 1.f;
    float newShadows = shadow;
    float newShadowSampleNum = 1;
    
    if (_ConvergeShadows)
    {
        float2 tempShadows = _ResultPrev.Load(int4(id.xyz, 0));
    
        float oldShadows = tempShadows.r;
        float oldShadowSampleNum = tempShadows.g;
    
        newShadows = oldShadows + shadow;
        newShadowSampleNum = oldShadowSampleNum + 1;    
    }

    _Result[id.xyz] = float2(newShadows, newShadowSampleNum);
}
