// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Main
#pragma enable_d3d11_debug_symbols

#include "../Includes/Common.hlsl"
#include "../Includes/RaymarchingHelpers.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
float _DistanceForHit;
int _MaxStepsOptimized;
float2 _ChunkSize;
float3 _SunDirection;
float4x4 _LightClipToWorld;
float4x4 _WorldToLightClip;
Texture2D<float> _HeightMap;

float4 _GrassColorRoughness;
float4 _WaterColorRoughness;
float4 _SnowColorRoughness;
float4 _SandColorRoughness;
float4 _ForestColorRoughness;
float4 _RockColorRoughness;

float _GrassLevel;
float _ForestLevel;
float _RockLevel;
float _SnowLevel;
float _OceanDepth;

RWTexture2D<float> _Result;

void BuildLightRay(float2 uv, out float3 ro, out float3 rd)
{
    float2 ndc = uv * 2.0 - 1.0;

    // Near plane in light clip space
    float4 clipNear = float4(ndc, 0.0, 1.0);

    float4 worldNear = mul(_LightClipToWorld, clipNear);
    worldNear.xyz /= worldNear.w;

    ro = worldNear.xyz;
    rd = normalize(_SunDirection);
}

[numthreads(16, 16, 1)]
void Main(uint3 id : SV_DispatchThreadID)
{
    
    // TODO: insert actual code here!
    uint2 dims;
    _Result.GetDimensions(dims.x, dims.y);

    if (id.x >= dims.x || id.y >= dims.y)
        return;

    float2 uv = (float2(id.xy) + 0.5) / float2(dims);
    
    float3 ro, rd;
    BuildLightRay(uv, ro, rd);

    float hitT;
    float hitHeight;
    
    bool hit = Raymarch(ro, rd, hitT, hitHeight, _MaxStepsOptimized, _DistanceForHit, 5e-1f, _ChunkSize, _HeightMap, linearClampSampler);

    if (hit)
    {
        float3 hitPos = ro + rd * hitT;

        float4 lightClip = mul(_WorldToLightClip, float4(hitPos, 1.0));
        lightClip.xyz /= lightClip.w;

        float depth = saturate(lightClip.z);
        _Result[id.xy] = depth;
    }
    else
    {
        _Result[id.xy] = 1.f;
    }
}
