// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Main
#pragma enable_d3d11_debug_symbols

#include "../Includes/Noise.hlsl"
#include "../Includes/BlueNoise.hlsl"
#include "../Includes/PBR.hlsl"
#include "../Includes/RaymarchingHelpers.hlsl"
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

uint _VisualizeTerrain;

//Ray marching parameters
int _MaxSteps;
int _MaxStepsOptimized;
float _DistanceForHit;

//Heightmap and info
Texture2DArray<float> _HeightMapArray;
StructuredBuffer<ChunkData> _Chunks;
int _ChunkCount;


Texture2D<float> _HeightMap;
Texture2D<float> _ShadowMap;
Texture2D<float> _CameraDepthTexture;
float2 _ChunkSize;
float3 _Scale;
float3 _Offset;

//Material values
float4 _GrassColorRoughness;
float4 _WaterColorRoughness;
float4 _SnowColorRoughness;
float4 _SandColorRoughness;
float4 _ForestColorRoughness;
float4 _RockColorRoughness;

float _GrassLevel;
float _ForestLevel;
float _RockLevel;
float _SnowLevel;
float _OceanDepth;

float _MaxHeight;
float _MinHeight;

float _Metallic;
uint _UseRaymarchOptimization;

//Other
float4 _SunDirectionIntensity;
float3 _SunColor;

RWTexture2D<float4> _Result;
Texture2D<float4> _Source;


float4x4 _CameraToWorld;
float4x4 _CameraInverseProjection;

float4 BiomeColor(float height)
{
    if (height <= _OceanDepth)
        return _WaterColorRoughness;
    else if (height < _GrassLevel)
        return _SandColorRoughness;
    else if (height <= _ForestLevel)
        return _GrassColorRoughness;
    else if (height <= _RockLevel)
        return _ForestColorRoughness;
    else if (height <= _SnowLevel)
        return _RockColorRoughness;
    else
        return float4(_SnowColorRoughness.rgb, 0.6f);
}


uint Hash(uint x)
{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

float Rand(inout uint seed)
{
    seed = Hash(seed);
    // Take lower 24 bits and normalize
    return (seed & 0x00FFFFFFu) / 16777216.0f; // 2^24
}

void CreateCoordinateSystem(const float3 N, out float3 Nt, out float3 Nb)
{
    if (abs(N.x) > abs(N.y))
        Nt = float3(N.z, 0, -N.x) / sqrt(N.x * N.x + N.z * N.z);
    else
        Nt = float3(0, -N.z, N.y) / sqrt(N.y * N.y + N.z * N.z);
    Nb = cross(N, Nt);
}

float3 CosineSampleHemisphere(float u1, float u2)
{
    float r = sqrt(u1);
    float phi = 2.0 * sPi * u2;
    float x = r * cos(phi);
    float y = r * sin(phi);
    float z = sqrt(1.0 - u1);
    return float3(x, y, z);
}

void MakeOrthonormalBasis(float3 n, out float3 t, out float3 b)
{
    float3 up = (abs(n.z) < 0.999f) ? float3(0, 0, 1) : float3(0, 1, 0);
    t = normalize(cross(up, n));
    b = cross(n, t);
}

float3 SampleConeDirection(float3 axis, float cosMax, float2 u)
{
    float cosTheta = lerp(cosMax, 1.0f, u.x);
    float sinTheta = sqrt(max(0.0f, 1.0f - cosTheta * cosTheta));
    float phi = 2.0f * sPi * u.y;

    float3 t, b;
    MakeOrthonormalBasis(axis, t, b);

    return normalize(t * (cos(phi) * sinTheta) + b * (sin(phi) * sinTheta) + axis * cosTheta);
}



float3 GetNormal(float3 p, float t, uint resolution)
{
    float2 texelWorldSize = _ChunkSize / resolution;
    float2 e = texelWorldSize;
    
    float hL = SampleTerrainHeight(p.xz - float2(e.x, 0), _Offset, _ChunkSize, _Scale.y, _HeightMap, linearClampSampler);
    float hR = SampleTerrainHeight(p.xz + float2(e.x, 0), _Offset, _ChunkSize, _Scale.y, _HeightMap, linearClampSampler);
    float hD = SampleTerrainHeight(p.xz - float2(0, e.y), _Offset, _ChunkSize, _Scale.y, _HeightMap, linearClampSampler);
    float hU = SampleTerrainHeight(p.xz + float2(0, e.y), _Offset, _ChunkSize, _Scale.y, _HeightMap, linearClampSampler);

    float dhdx = (hR - hL) / (2.0f * e.x);
    float dhdz = (hU - hD) / (2.0f * e.y);

    float3 n = normalize(float3(-dhdx, 1.0f, -dhdz));

    return n;
}

float SampleShadowMap(float3 worldPos, float3 lightDir)
{
    float2 uv = (worldPos.xz - _Offset.xz) / _ChunkSize; // uv.y *= -1;

    if (uv.x < 0.0 || uv.x > 1.0 ||
        uv.y < 0.0 || uv.y > 1.0)
        return 1.0;

    return _ShadowMap.SampleLevel(linearClampSampler, uv, 0);
}

float3 ReconstructWorldPos(uint2 pixel, uint2 dims)
{
    float2 uv = (float2(pixel) + 0.5) / float2(dims);

    float2 ndc = uv * 2.0 - 1.0;
    ndc.y = -ndc.y; // Unity screen UV to clip Y

    float depth = _CameraDepthTexture.Load(int3(pixel, 0));

    float4 clip = float4(ndc, depth, 1.0);

    float4 view = mul(_CameraInverseProjection, clip);
    view /= view.w;

    float4 world = mul(_CameraToWorld, float4(view.xyz, 1.0));
    return world.xyz;
}

[numthreads(16,16,1)]
void Main(uint3 id : SV_DispatchThreadID)
{   
    uint2 dims;
    _Result.GetDimensions(dims.x, dims.y);
    
    if (id.x >= dims.x || id.y >= dims.y)
        return;

    float2 uv = (float2(id.xy) + 0.5) / float2(dims.x, dims.y);
    
    // 0..1 -> -1..1
    float2 ndc = uv * 2.0 - 1.0;

    // Flip Y if needed
    ndc.y = -ndc.y;

    // Point on the far plane in clip space
    float4 clipPos = float4(ndc, 1.0, 1.0);

    // Back to view space
    float4 viewPos = mul(_CameraInverseProjection, clipPos);
    viewPos /= viewPos.w;

    // Direction in view space
    float3 rayDirView = normalize(viewPos.xyz);

    // Transform direction to world space
    float3 rayDirection = normalize(mul((float3x3) _CameraToWorld, rayDirView));

    float3 cameraPos = _WorldSpaceCameraPos;
    
    float2 shadowUV = uv;
    shadowUV.y = 1 - shadowUV.y;
    float testValue = _HeightMapArray.SampleLevel(linearClampSampler, float3(uv, 0.f), 0.f);
    
    float elevation = 0;
    float3 col = 0;
    float shadow;
    float hitT1 = 0.0f;
    float3 hitPos;
    float debugGrid = 0.f;

    bool hit = false;
    
    float3 sunDir = normalize(_SunDirectionIntensity.xyz);
    float3 worldPos = ReconstructWorldPos(id.xy, dims);
    
    shadow = SampleShadowMap(worldPos, sunDir);
    
    uint flippedY = dims.y - 1 - id.y;
    float3 rtColor = _Source.Load(int3(id.x, flippedY, 0)).rgb;
    col.rgb = rtColor;

    if (_VisualizeTerrain)
    {        
        bool hit = false;
        float closestT = 1e20;
        int closestChunk = -1;
        float closestElevation = 0.0;
        bool chunkHit;
        for (int i = 0; i < _ChunkCount; i++)
        {
            ChunkData chunk = _Chunks[i];

            float hitT;
            float elevation;

            if (!_UseRaymarchOptimization)
                chunkHit = RaymarchChunk(
                    cameraPos,
                    rayDirection,
                    hitT,
                    elevation,
                    _MaxSteps,
                    _DistanceForHit,
                    2e-4f,
                    chunk,
                    _HeightMapArray,
                    linearClampSampler);
            else
                 chunkHit = TraverseHeightfieldMaxMipChunk(cameraPos, rayDirection, hitT, elevation, _DistanceForHit, linearClampSampler,
                _MaxStepsOptimized, _HeightMapArray, chunk);
                                                                                 
        
            if (chunkHit && hitT < closestT)
            {
                hit = true;
                closestT = hitT;
                closestElevation = elevation;
                closestChunk = 0;
                col.rgb = closestElevation.xxx / 10000.f;
            }
        }

        //if (hit)
        //{
        //    uint2 heightmapDimensions;
        //    _HeightMap.GetDimensions(heightmapDimensions.x, heightmapDimensions.y);
        //    float3 p = cameraPos + rayDirection * hitT1;
        //    float3 n = GetNormal(p, hitT1, heightmapDimensions.x);
        //    float4 biomeValue = BiomeColor(elevation);
        
        //    PBRMaterial mat;
        //    mat.baseColor = biomeValue.rgb;
        //    mat.roughness = biomeValue.a;
        //    mat.metallic = _Metallic;
        //    mat.normal = n;
        //    mat.F0 = float3(0.02, 0.02, 0.02);
        //    mat.F0 = lerp(mat.F0, mat.baseColor.rgb, mat.metallic);
        //    mat.diffuse = lerp(mat.baseColor.rgb, float3(0.0, 0.0, 0.0), mat.metallic);
        
        //    float3 viewDirection = normalize(cameraPos - p);
        //    float3 sunDir = -normalize(_SunDirectionIntensity.xyz);
        
        //    float3 diffuse = 0.f;
        //    float3 specular = 0.f;
        //    GetBRDF(mat, viewDirection, sunDir, _SunColor, _SunDirectionIntensity.w, 1.f, diffuse, specular);
        
        //    float3 ambientColor = 1.f;
        //    GetBRDF(mat, viewDirection, viewDirection, ambientColor, AMBIENT_INTENSITY, 1.f, diffuse, specular);

        //    col.rgb = diffuse + specular;
        //}

    }
    
    //col.rgb *= shadow;
    _Result[id.xy] = float4(col.rgb, 1.0);


}    
